version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./uploads:/app/uploads
    ports:
      - "3005:3000"
    environment:
      - HOST=${HOST}
      - NEXT_PUBLIC_HOST=${HOST}