name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PPYNSRVKEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "."
          target: "/opt/appload"

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PPYNSRVKEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /opt/appload
            export HOST=${{ secrets.HOST }}
            export NEXT_PUBLIC_HOST=${{ secrets.HOST }}
            docker compose build
            docker compose stop
            docker compose up -d
